### ISSUE TITLE
Task fails when NuGet packages folder differs from default one

### ISSUE THREAD

**Issue by tichaczech** [emerbrito/ILMerge-MSBuild-Task#6]
In our environment, packages are placed in different folder than in default "packages" in solution directory. Check NuGet configuration file for more info, but basically it can be set in NuGet.Config file like on example below.

```
<config>
	<add key="repositoryPath" value="..\_packages" />
</config>
```

Build output below
```
error MSB4018: The "MergeTask" task failed unexpectedly.
error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'W:\compunet.cz\Sirwisa.LogManager.WES\packages'.
error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
error MSB4018:    at System.IO.FileSystemEnumerableIterator`1.CommonInit()
error MSB4018:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
error MSB4018:    at System.IO.Directory.EnumerateDirectories(String path, String searchPattern, SearchOption searchOption)
error MSB4018:    at ILMerge.MsBuild.Task.ExeLocationHelper.TryILMergeInSolutionDir(String solutionDir, String& executablePath) in D:\Dev\Repos\ILMerge-MSBuild-Task\ILMerge.MSBuild.Task\ILMerge.MSBuild.Task\ExeLocationHelper.cs:line 48
error MSB4018:    at ILMerge.MsBuild.Task.MergeTask.GetILMergePath() in D:\Dev\Repos\ILMerge-MSBuild-Task\ILMerge.MSBuild.Task\ILMerge.MSBuild.Task\MergeTask.cs:line 475
error MSB4018:    at ILMerge.MsBuild.Task.MergeTask.Execute() in D:\Dev\Repos\ILMerge-MSBuild-Task\ILMerge.MSBuild.Task\ILMerge.MSBuild.Task\MergeTask.cs:line 148
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by slahn** [comment]
We've also hit this issue.
This is because the merge tasks looks for the packages folder relative to the solution directory, not relative to the task DLL.
For now we're working around it by copying ilmerge.exe into the target folder (\bin\Debug, \bin\Release), since that location is searched before the packages folder.

**Comment by emerbrito** [comment]
First of all thanks for collaborating. This one fell through the cracks of my inbox and I missed it.
Anyways, it makes complete sense that it should "figure out" the location instead of assuming a default. I will work on it and post an update.

**Comment by emerbrito** [comment]
On a second thought, the parameter `AlternativeILMergePath` found in the configuration file exists to deals with this kind of scenario [(config file)](AlternativeILMergePath). You should be able to specify an alternative path when your environment deviates from default values. I'm changing the label on this from "bug" to "help wanted" since the package already has built in functionality to address the issue.

**Comment by emerbrito** [comment]
Even though you can use `AlternativeILMergePath` parameter a solution for the issue presented here, in the latest update (to be published today in the nugget repository), the code will be able to figure out the custom path of your nugget packages, saving you the trouble of hard-coding a location for it.
